services:
  - type: web
    name: javainhire-backend
    runtime: java
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-cv7hfptsvqrc739p2v70-a.oregon-postgres.render.com:5432/javainhire_db_render
      - key: SPRING_DATASOURCE_USERNAME
        value: javainhire_db_render_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: MgZNr99dAvxSJyowDmTQy8MrOXQpD5uK